// resources/react/components/filters/TextFilter.tsx
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useState, type KeyboardEvent } from 'react';
import { useWatch } from '../../composables/useWatch';

export interface TextFilterProps {
    name: string;
    label: string;
    modelValue?: string | null;
    placeholder?: string;
    type?: 'text' | 'email' | 'url' | 'number';
    onUpdateModelValue?: (value: string | null) => void;
}

export default function TextFilter({
    name,
    label,
    modelValue = null,
    placeholder = 'Enter text...',
    type = 'text',
    onUpdateModelValue,
}: TextFilterProps) {
    const [localValue, setLocalValue] = useState<string>(modelValue || '');

    useWatch(modelValue, (newValue) => {
        setLocalValue(newValue || '');
    });

    const handleInput = () => {
        const value = localValue.trim();
        onUpdateModelValue?.(value || null);
    };

    return (
        <div className="flex flex-col gap-2">
            <Label htmlFor={name} className="text-sm font-medium">
                {label}
            </Label>
            <Input
                id={name}
                value={localValue}
                type={type}
                placeholder={placeholder}
                onChange={(event) => setLocalValue(event.target.value)}
                onBlur={handleInput}
                onKeyUp={(event: KeyboardEvent<HTMLInputElement>) => {
                    if (event.key === 'Enter') handleInput();
                }}
            />
        </div>
    );
}

// resources/js/components/filters/TextFilter.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'

interface TextFilterProps {
  name: string
  label: string
  modelValue?: string | null
  placeholder?: string
  type?: 'text' | 'email' | 'url' | 'number'
}

const props = withDefaults(defineProps<TextFilterProps>(), {
  modelValue: null,
  placeholder: 'Enter text...',
  type: 'text',
})

const emit = defineEmits<{
  'update:modelValue': [value: string | null]
}>()

const localValue = ref(props.modelValue || '')

watch(() => props.modelValue, (newValue) => {
  localValue.value = newValue || ''
})

const handleInput = () => {
  const value = localValue.value.trim()
  emit('update:modelValue', value || null)
}
</script>

<template>
  <div class="flex flex-col gap-2">
    <Label :for="name" class="text-sm font-medium">
      {{ label }}
    </Label>
    <Input
      :id="name"
      v-model="localValue"
      :type="type"
      :placeholder="placeholder"
      @blur="handleInput"
      @keyup.enter="handleInput"
    />
  </div>
</template>
