// resources/js/components/grid-columns/ImageGridColumn.vue
<script setup lang="ts">
import { computed } from 'vue'

interface ImageGridColumnProps {
  value: any
  imageWidth?: string | number | null
  imageHeight?: string | number | null
  square?: boolean
  circular?: boolean
  stacked?: boolean
  ring?: number
  overlap?: number
  limit?: number | null
  limitedRemainingText?: boolean
  limitedRemainingTextSize?: string
  wrap?: boolean
  disk?: string | null
  visibility?: string | null
  defaultImageUrl?: string | null
  checkFileExistence?: boolean
  extraImgAttributes?: Record<string, any>
  description?: string | null
  descriptionPosition?: 'above' | 'below'
}

const props = withDefaults(defineProps<ImageGridColumnProps>(), {
  imageWidth: null,
  imageHeight: null,
  square: false,
  circular: false,
  stacked: false,
  ring: 3,
  overlap: 4,
  limit: null,
  limitedRemainingText: false,
  limitedRemainingTextSize: 'sm',
  wrap: false,
  disk: null,
  visibility: null,
  defaultImageUrl: null,
  checkFileExistence: true,
  extraImgAttributes: () => ({}),
  description: null,
  descriptionPosition: 'below',
})

const images = computed(() => {
  // Show default image if no value but defaultImageUrl is set
  if (!props.value) return props.defaultImageUrl ? [props.defaultImageUrl] : []
  return Array.isArray(props.value) ? props.value : [props.value]
})

const displayImages = computed(() => {
  if (!props.limit) return images.value
  return images.value.slice(0, props.limit)
})

const remainingCount = computed(() => {
  if (!props.limit || images.value.length <= props.limit) return 0
  return images.value.length - props.limit
})

const sizeStyle = computed(() => {
  const style: Record<string, string> = {}

  if (props.imageWidth) {
    style.width = typeof props.imageWidth === 'number' ? `${props.imageWidth}px` : props.imageWidth
  }

  if (props.imageHeight) {
    style.height = typeof props.imageHeight === 'number' ? `${props.imageHeight}px` : props.imageHeight
  }

  return style
})

const shapeClass = computed(() => {
  if (props.circular) return 'rounded-full'
  if (props.square) return 'aspect-square'
  return 'rounded-md'
})

const ringClass = computed(() => {
  const ringMap: Record<number, string> = {
    0: 'ring-0',
    1: 'ring-1',
    2: 'ring-2',
    3: 'ring',
    4: 'ring-4',
    5: 'ring-[5px]',
    6: 'ring-[6px]',
    7: 'ring-[7px]',
    8: 'ring-8',
  }
  return ringMap[props.ring] || 'ring'
})

const overlapClass = computed(() => {
  // Negative margin for overlap
  const overlapMap: Record<number, string> = {
    0: '',
    1: '-ml-1',
    2: '-ml-2',
    3: '-ml-3',
    4: '-ml-4',
    5: '-ml-5',
    6: '-ml-6',
    7: '-ml-7',
    8: '-ml-8',
  }
  return overlapMap[props.overlap] || '-ml-4'
})

const remainingSizeClass = computed(() => {
  const sizeMap: Record<string, string> = {
    'xs': 'text-xs',
    'sm': 'text-sm',
    'md': 'text-base',
    'lg': 'text-lg',
    'xl': 'text-xl',
  }
  return sizeMap[props.limitedRemainingTextSize] || 'text-sm'
})

const getImageUrl = (image: string): string => {
  // If it's already an absolute URL, return it
  if (image.startsWith('http://') || image.startsWith('https://') || image.startsWith('data:')) {
    return image
  }

  // Handle disk and visibility for Laravel storage
  // If visibility is 'public' or disk is 'public', use /storage/ path
  // Otherwise, this should be a temporary URL generated by the backend
  if (props.visibility === 'public' || props.disk === 'public') {
    return `/storage/${image}`
  }

  // For non-public storage, assume the backend will provide temporary URLs
  // If it's a relative path, prepend /storage/ as default
  if (!image.startsWith('/')) {
    return `/storage/${image}`
  }

  return image
}

const handleImageError = (event: Event) => {
  const imgElement = event.target as HTMLImageElement
  if (!props.defaultImageUrl) return
  // Resolve the fallback the same way as the rendered src, then compare normalized URLs:
  // only fall back once, so a failing default image can't cause an error/reload loop
  const fallbackUrl = getImageUrl(props.defaultImageUrl)
  if (imgElement.getAttribute('src') !== fallbackUrl) {
    imgElement.src = fallbackUrl
  }
}
</script>

<template>
  <div class="flex flex-col gap-1">
    <!-- Description above -->
    <div v-if="description && descriptionPosition === 'above'" class="text-[11px] text-muted-foreground/70">
      {{ description }}
    </div>

    <!-- Main content -->
    <div :class="wrap ? 'flex flex-wrap gap-1.5' : 'flex items-center'">
      <!-- Stacked images -->
      <div v-if="stacked" class="flex items-center">
        <div
          v-for="(image, index) in displayImages"
          :key="index"
          :class="[
            'relative',
            index > 0 && overlapClass,
          ]"
        >
          <img
            :src="getImageUrl(image)"
            :alt="`Image ${index + 1}`"
            :style="sizeStyle"
            :class="[
              shapeClass,
              ringClass,
              'ring-background object-cover',
            ]"
            v-bind="extraImgAttributes"
            @error="handleImageError"
          />
        </div>

        <span
          v-if="limitedRemainingText && remainingCount > 0"
          :class="[
            'ml-2 text-muted-foreground font-medium',
            remainingSizeClass,
          ]"
        >
          +{{ remainingCount }}
        </span>
      </div>

      <!-- Regular images -->
      <template v-else>
        <img
          v-for="(image, index) in displayImages"
          :key="index"
          :src="getImageUrl(image)"
          :alt="`Image ${index + 1}`"
          :style="sizeStyle"
          :class="[
            shapeClass,
            'object-cover',
          ]"
          v-bind="extraImgAttributes"
          @error="handleImageError"
        />

        <span
          v-if="limitedRemainingText && remainingCount > 0"
          :class="[
            'text-muted-foreground font-medium',
            remainingSizeClass,
          ]"
        >
          +{{ remainingCount }}
        </span>
      </template>
    </div>

    <!-- Description below -->
    <div v-if="description && descriptionPosition === 'below'" class="text-[11px] text-muted-foreground/70">
      {{ description }}
    </div>
  </div>
</template>

// resources/react/components/grid-columns/ImageGridColumn.tsx
import { cn } from '@/lib/utils';
import type { CSSProperties, SyntheticEvent } from 'react';

export interface ImageGridColumnProps {
    value: any;
    imageWidth?: string | number | null;
    imageHeight?: string | number | null;
    square?: boolean;
    circular?: boolean;
    stacked?: boolean;
    ring?: number;
    overlap?: number;
    limit?: number | null;
    limitedRemainingText?: boolean;
    limitedRemainingTextSize?: string;
    wrap?: boolean;
    disk?: string | null;
    visibility?: string | null;
    defaultImageUrl?: string | null;
    checkFileExistence?: boolean;
    extraImgAttributes?: Record<string, any>;
    description?: string | null;
    descriptionPosition?: 'above' | 'below';
}

const EMPTY_ATTRIBUTES: Record<string, any> = {};

const ringMap: Record<number, string> = {
    0: 'ring-0',
    1: 'ring-1',
    2: 'ring-2',
    3: 'ring',
    4: 'ring-4',
    5: 'ring-[5px]',
    6: 'ring-[6px]',
    7: 'ring-[7px]',
    8: 'ring-8',
};

// Negative margin for overlap
const overlapMap: Record<number, string> = {
    0: '',
    1: '-ml-1',
    2: '-ml-2',
    3: '-ml-3',
    4: '-ml-4',
    5: '-ml-5',
    6: '-ml-6',
    7: '-ml-7',
    8: '-ml-8',
};

const remainingSizeMap: Record<string, string> = {
    xs: 'text-xs',
    sm: 'text-sm',
    md: 'text-base',
    lg: 'text-lg',
    xl: 'text-xl',
};

/**
 * Split `v-bind="extraImgAttributes"` into DOM props, merging `class`/`style` like Vue does.
 */
function splitExtraAttributes(extra: Record<string, any>): { rest: Record<string, any>; className?: string; style?: CSSProperties } {
    const { class: extraClass, style: extraStyle, ...rest } = extra || {};

    return {
        rest,
        className: typeof extraClass === 'string' ? extraClass : undefined,
        style: extraStyle && typeof extraStyle === 'object' ? (extraStyle as CSSProperties) : undefined,
    };
}

export default function ImageGridColumn({
    value,
    imageWidth = null,
    imageHeight = null,
    square = false,
    circular = false,
    stacked = false,
    ring = 3,
    overlap = 4,
    limit = null,
    limitedRemainingText = false,
    limitedRemainingTextSize = 'sm',
    wrap = false,
    disk = null,
    visibility = null,
    defaultImageUrl = null,
    extraImgAttributes = EMPTY_ATTRIBUTES,
    description = null,
    descriptionPosition = 'below',
}: ImageGridColumnProps) {
    const images: any[] = !value
        ? // Show default image if no value but defaultImageUrl is set
          defaultImageUrl
            ? [defaultImageUrl]
            : []
        : Array.isArray(value)
          ? value
          : [value];

    const displayImages = !limit ? images : images.slice(0, limit);

    const remainingCount = !limit || images.length <= limit ? 0 : images.length - limit;

    const sizeStyle: CSSProperties = {};

    if (imageWidth) {
        sizeStyle.width = typeof imageWidth === 'number' ? `${imageWidth}px` : imageWidth;
    }

    if (imageHeight) {
        sizeStyle.height = typeof imageHeight === 'number' ? `${imageHeight}px` : imageHeight;
    }

    const shapeClass = circular ? 'rounded-full' : square ? 'aspect-square' : 'rounded-md';
    const ringClass = ringMap[ring] || 'ring';
    const overlapClass = overlapMap[overlap] || '-ml-4';
    const remainingSizeClass = remainingSizeMap[limitedRemainingTextSize] || 'text-sm';

    const getImageUrl = (image: string): string => {
        // If it's already an absolute URL, return it
        if (image.startsWith('http://') || image.startsWith('https://') || image.startsWith('data:')) {
            return image;
        }

        // Handle disk and visibility for Laravel storage
        // If visibility is 'public' or disk is 'public', use /storage/ path
        // Otherwise, this should be a temporary URL generated by the backend
        if (visibility === 'public' || disk === 'public') {
            return `/storage/${image}`;
        }

        // For non-public storage, assume the backend will provide temporary URLs
        // If it's a relative path, prepend /storage/ as default
        if (!image.startsWith('/')) {
            return `/storage/${image}`;
        }

        return image;
    };

    const handleImageError = (event: SyntheticEvent<HTMLImageElement>) => {
        const imgElement = event.currentTarget;
        if (!defaultImageUrl) return;
        // Resolve the fallback the same way as the rendered src, then compare normalized URLs:
        // only fall back once, so a failing default image can't cause an error/reload loop
        const fallbackUrl = getImageUrl(defaultImageUrl);
        if (imgElement.getAttribute('src') !== fallbackUrl) {
            imgElement.src = fallbackUrl;
        }
    };

    const extra = splitExtraAttributes(extraImgAttributes);

    return (
        <div className="flex flex-col gap-1">
            {/* Description above */}
            {description && descriptionPosition === 'above' && (
                <div className="text-[11px] text-muted-foreground/70">{description}</div>
            )}

            {/* Main content */}
            <div className={wrap ? 'flex flex-wrap gap-1.5' : 'flex items-center'}>
                {stacked ? (
                    // Stacked images
                    <div className="flex items-center">
                        {displayImages.map((image: any, index: number) => (
                            <div key={index} className={cn('relative', index > 0 && overlapClass)}>
                                <img
                                    src={getImageUrl(image)}
                                    alt={`Image ${index + 1}`}
                                    {...extra.rest}
                                    style={{ ...sizeStyle, ...extra.style }}
                                    className={cn(shapeClass, ringClass, 'ring-background object-cover', extra.className)}
                                    onError={handleImageError}
                                />
                            </div>
                        ))}

                        {limitedRemainingText && remainingCount > 0 && (
                            <span className={cn('ml-2 text-muted-foreground font-medium', remainingSizeClass)}>+{remainingCount}</span>
                        )}
                    </div>
                ) : (
                    // Regular images
                    <>
                        {displayImages.map((image: any, index: number) => (
                            <img
                                key={index}
                                src={getImageUrl(image)}
                                alt={`Image ${index + 1}`}
                                {...extra.rest}
                                style={{ ...sizeStyle, ...extra.style }}
                                className={cn(shapeClass, 'object-cover', extra.className)}
                                onError={handleImageError}
                            />
                        ))}

                        {limitedRemainingText && remainingCount > 0 && (
                            <span className={cn('text-muted-foreground font-medium', remainingSizeClass)}>+{remainingCount}</span>
                        )}
                    </>
                )}
            </div>

            {/* Description below */}
            {description && descriptionPosition === 'below' && (
                <div className="text-[11px] text-muted-foreground/70">{description}</div>
            )}
        </div>
    );
}
